### ISSUE TITLE
关于本项目代码使用权限的询问。

### ISSUE THREAD

**Issue by CordellWL** [SXX19950910/manifest-design#3]
你好：
       我们在github上看到一个关于你写的关于快递标签布局涉及的开源组件，感觉写的挺好的。
       我们这边公司里面有个商用项目，打算基于你的这个开源组件再做一些定制化的修改。
       因为你当时在github上没有写明开源协议，我们想请教一下，针对这个开源组件，我们开发时能否像类似于于BSD或者MIT 协议的开源产品一样使用，甚至是最好的项目商用。
       或者你能否提供一个声明协议。
       盼望能得到您的回复。

**Comment by SXX19950910** [comment]
可以。
