### ISSUE TITLE
是否能实现批量打印呢？

### ISSUE THREAD

**Issue by eggbucket** [SXX19950910/manifest-design#5]
是否能实现批量打印呢？分页打印多张、有时候需要一次打印多张快递面单（不同的客户名称、地址）

**Comment by SXX19950910** [comment]
> 是否能实现批量打印呢？分页打印多张、有时候需要一次打印多张快递面单（不同的客户名称、地址）



> 是否能实现批量打印呢？分页打印多张、有时候需要一次打印多张快递面单（不同的客户名称、地址）

1.批量打印你可以通过循环调用模板的打印方法实现  2.目前模板变量的功能正在开发中，后续会提供相应API进行调用，使用”${变量}“形式的字符串即视为变量.
```javascript
// feature
// 此方法会将模板中的变量统一替换成你设定的值
this.$refs.template.print({ paramsKey1:  value, paramsKey2:  value })
```

**Comment by eggbucket** [comment]
这是一种实现方案、但是有一种场景、比如我需打印1000张，意味着需要循环调用1000次打印方法，会不会有效率问题呢？是否可以考虑生成pdf或者自动分页的方式，一次打印出这1000张不同客户的单据呢？

**Comment by SXX19950910** [comment]
> 这是一种实现方案、但是有一种场景、比如我需打印1000张，意味着需要循环调用1000次打印方法，会不会有效率问题呢？是否可以考虑生成pdf或者自动分页的方式，一次打印出这1000张不同客户的单据呢？

没错，这种场景也会存在，未来会考虑加入该功能，但这取决于lodop控件的支持情况。

**Comment by eggbucket** [comment]
可以转成pdf，通过pdf打印，这种多张的对无感知没那么重要
