### ISSUE TITLE
这个矩形打印预览不起作用

### ISSUE THREAD

**Issue by mcguire-w** [SXX19950910/manifest-design#7]
![image](https://user-images.githubusercontent.com/48664370/142579123-a7eac56d-7478-4b89-baaf-0f9bebfd6e85.png)

**Comment by SXX19950910** [comment]
> ![image](https://user-images.githubusercontent.com/48664370/142579123-a7eac56d-7478-4b89-baaf-0f9bebfd6e85.png)

原因：预览时对应矩形元素的样式规则没找到
处理结果：已修复该问题，谢谢反馈。
