### ISSUE TITLE
node 16.13.0 版本 下载依赖失败

### ISSUE THREAD

**Issue by mcguire-w** [SXX19950910/manifest-design#8]
![image](https://user-images.githubusercontent.com/48664370/143374294-a251cf21-0f62-43b4-bd36-88eb3e921377.png)

**Comment by SXX19950910** [comment]
> ![image](https://user-images.githubusercontent.com/48664370/143374294-a251cf21-0f62-43b4-bd36-88eb3e921377.png)

推荐使用yarn安装

**Comment by mcguire-w** [comment]
![image](https://user-images.githubusercontent.com/48664370/143433037-a236a1ab-7601-4fb5-8c5d-18032dc35fa1.png)
yarn 也不行

**Comment by SXX19950910** [comment]
> ![image](https://user-images.githubusercontent.com/48664370/143433037-a236a1ab-7601-4fb5-8c5d-18032dc35fa1.png) yarn 也不行

node-sass， sass-loader 可以不要使用我用的版本，根据你系统及node版本安装对应的版本就好了， 建议你试着安装最新版本的node-sass

**Comment by kasbin** [comment]
降级node为V14可用
